---
- name: Copy environment variables file
  template:
    src: env.j2
    dest: "{{ express_app_path }}/.env"
    mode: 0644
    owner: "{{ express_system_user }}"
    group: "{{ express_system_group }}"
  changed_when: false

- name: Install Javascript requirements
  become: true
  become_user: "{{ express_system_user }}"
  yarn:
    state: present
    path: "{{ item }}"
  with_items: "{{ express_package_json_paths }}"
  tags:
    - molecule-idempotence-notest

- name: Compile Javascript
  command:
    cmd: yarn build
    chdir: "{{ express_app_path }}"
  become: true
  become_user: "{{ express_system_user }}"
  changed_when: false

# creates a sym-link express_codebase_path; that points to the express checkout path
- name: Make the new codebase current
  file:
    src: "{{ express_checkout_path }}"
    dest: "{{ express_codebase_path }}"
    state: link
    force: true
    owner: "{{ express_system_user }}"
    group: "{{ express_system_group }}"
  tags:
    - molecule-idempotence-notest

- name: Restart express pm2 process
  become: true
  become_user: "{{ express_system_user }}"
  command: "{{ express_pm2_path }} restart {{ express_service_name }}"
  args:
    chdir: "{{ express_app_path }}"
  register: pm2_process
  ignore_errors: true
  changed_when: false

- name: set express_service_exists fact
  set_fact:
    express_service_not_exists: "{{ pm2_process.rc != 0 }}"

- name: set express_service_exists fact
  set_fact:
    express_service_exists: "{{ not express_service_not_exists }}"

- name: creating pm2 process
  block:
    - name: Delete express pm2 process
      become: true
      become_user: "{{ express_system_user }}"
      command: "{{ express_pm2_path }} delete all"
      notify:
        - start_express_service
      ignore_errors: true


    - name: Start express pm2 app
      become: true
      become_user: "{{ express_system_user }}"
      command: >
        {{ express_pm2_path }} start dist/index.js
        --name {{ express_service_name }}
      args:
        chdir: "{{ express_app_path }}"

    - name: save the current PM2 running list
      become: true
      become_user: "{{ express_system_user }}"
      command: "{{ express_pm2_path }} save"
  when: express_service_not_exists
  notify:
    - start_express_service

- name: delete the old startup file
  become: true
  become_user: "root"
  command: >
    {{ express_pm2_path }} unstartup
    -u {{ express_system_user }}
    --service-name {{ express_service_name }}
    --hp {{ express_system_user_home }}
  ignore_errors: true
  notify:
    - start_express_service
  tags:
    - molecule-idempotence-notest

- name: Generate an express PM2 init service file
  become: true
  become_user: "root"
  command: "{{ express_pm2_path }} startup  -u {{ express_system_user }}
    --hp {{ express_system_user_home }}
    --service-name {{ express_service_name }}"
  notify:
    - start_express_service
  tags:
    - molecule-idempotence-notest