---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible
    # command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - -vvvv
  playbook:
    prepare: prepare.yml
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
